/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Optional;

public class App {

    public static void main(String[] args) {
        WeatherForecastApiClient client = new WeatherForecastApiClient();
        Optional<String> forecast = client.getWeatherForecast();
        if (forecast.isPresent()) {
            System.out.println(forecast.get());
        } else {
            System.out.println("Failed to get the weather forecast.");
        }
    }
}
