/*
 * This source file was generated by the Gradle 'init' task
 */
package weatherapiapp;

public class App {

    public static void main(String[] args) {
        WeatherForecastApiClient client = new WeatherForecastApiClient();
        
        String forecast = client.getWeatherForecast();

        WeatherForecastParser weatherForecastParser = new WeatherForecastParser();

        WeatherForecast weatherForecast = weatherForecastParser.ToWeatherForecastObject(forecast);

        WeatherForecast.Properties properties = weatherForecast.getProperties();

        for (WeatherForecast.Period period : properties.getPeriods()) {
            System.out.println(period.toString());
            System.out.println();
        }
    }
}