/*
 * This source file was generated by the Gradle 'init' task
 */
package weatherapiapp;

//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class WeatherApiAppTest {
    // @Test void appHasAGreeting() {
    // WeatherApiApp classUnderTest = new WeatherApiApp();
    // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
